import './styles.css';

const BASE = import.meta.env.BASE_URL || '/';
const page = document.body.dataset.page;
const app = document.querySelector('#app');
const cache = new Map();
const fmt = new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const fmtDay = new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'long',year:'numeric'});

const esc = (s='') => String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const q = (k) => new URLSearchParams(location.search).get(k);
const dataUrl = (rel) => `${BASE}data/${rel}`.replace(/([^:]\/)\/+ /g,'$1');
async function load(rel){ if(cache.has(rel)) return cache.get(rel); const p=fetch(`${BASE}data/${rel}`).then(r=>{if(!r.ok) throw new Error(`${rel}: HTTP ${r.status}`); return r.json();}); cache.set(rel,p); return p; }
async function core(){ const [config,races,series,tracks]=await Promise.all([load('config.json'),load('races.json'),load('series.json'),load('tracks.json')]); return {config,races,series,tracks,seriesMap:new Map(series.map(x=>[x.slug,x])),trackMap:new Map(tracks.map(x=>[x.slug,x]))}; }
function status(r,now=new Date()){ const a=new Date(r.startUtc),b=new Date(r.endUtc||r.startUtc); return now<a?'upcoming':now<=b?'live':'finished'; }
function statusLabel(s){ return s==='live'?'LIVE':s==='finished'?'BEENDET':'BEVORSTEHEND'; }
function rel(d,now=new Date()){ const ms=d-now,abs=Math.abs(ms),past=ms<0; const min=Math.round(abs/60000),hr=Math.round(abs/3600000),day=Math.round(abs/86400000); let x=min<1?'gerade eben':min<60?`${min} Min`:hr<24?`${hr} h`:day<30?`${day} Tag${day===1?'':'e'}`:new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(d); return min<1?x:(past?`vor ${x}`:`in ${x}`); }
function duration(r){ let ms=new Date(r.endUtc)-new Date(r.startUtc); const h=Math.round(ms/3600000); return h>=24&&h%24===0?`${h/24} Tage`:`${h} h`; }
function shell(content,title=''){ document.title=`${title?title+' · ':''}RACE PIT WALL`; app.innerHTML=`<div id="livebar"></div>${header()}<main class="wrap">${content}</main>${footer()}`; tickClock(); liveBar(); }
function header(){ const file=location.pathname.split('/').pop()||'index.html'; const links=[['index.html','PIT WALL'],['rennen.html','RENNEN'],['kalender.html','KALENDER'],['serien.html','SERIEN'],['watchlist.html','WATCHLIST'],['about.html','ABOUT']]; return `<header class="header"><a class="brand" href="${BASE}">RACE <b>PIT WALL</b></a><nav>${links.map(([h,l])=>`<a class="${file===h?'active':''}" href="${BASE+h}">${l}</a>`).join('')}</nav><span id="clock" class="clock">--:--:--</span></header>`; }
function footer(){ return `<footer class="footer"><div>RACE PIT WALL · inoffizielles Fan-Projekt</div><div>Keine Verbindung zu FIA, ACO, ADAC, SRO oder Veranstaltern · Alle Zeiten lokal · Angaben ohne Gewähr</div></footer>`; }
function tickClock(){ const e=document.querySelector('#clock'); if(!e)return; const f=()=>e.textContent=new Date().toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit',second:'2-digit'}); f(); setInterval(f,1000); }
async function liveBar(){ try{ const races=await load('races.json'); const live=races.filter(r=>status(r)==='live'); const e=document.querySelector('#livebar'); if(!e||!live.length)return; e.innerHTML=`<div class="livebar">${live.map(r=>`<a href="${BASE}race.html?slug=${encodeURIComponent(r.slug)}"><span class="pulse"></span><b>LIVE</b> ${esc(r.name)} <span>${duration(r)}</span></a>`).join('')}</div>`;}catch{} }
function badge(r){ const s=status(r); return `<span class="badge ${s}">${s==='live'?'<i></i>':''}${statusLabel(s)}</span>`; }
function classes(r){ return (r.classTags||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join(''); }
function raceCard(r,c){ const s=c.seriesMap.get(r.seriesSlug),t=c.trackMap.get(r.trackSlug),d=new Date(r.startUtc); return `<a class="race-card" href="${BASE}race.html?slug=${encodeURIComponent(r.slug)}"><div class="race-top"><span class="series">${esc(s?.shortName||r.seriesSlug)}</span>${badge(r)}</div><h3>${esc(r.name)}</h3><p>${esc(t?.name||r.trackSlug)}</p><div class="when"><b>${fmt.format(d).toUpperCase()}</b><span>${status(r)==='upcoming'?rel(d):status(r)==='live'?'läuft jetzt':rel(new Date(r.endUtc))}</span></div><div class="pills">${classes(r)}</div>${r.startTimeConfirmed===false?'<small>Startzeit tbc</small>':''}</a>`; }
function hero(r,c){ const s=c.seriesMap.get(r.seriesSlug),t=c.trackMap.get(r.trackSlug); return `<a class="hero" href="${BASE}race.html?slug=${encodeURIComponent(r.slug)}"><div class="eyebrow">${badge(r)} <span>FEATURED · ${esc(s?.shortName||'')}</span></div><h1>${esc(r.name)}</h1><div class="hero-meta"><span>⌖ ${esc(t?.name||r.trackSlug)}</span><span>⚑ ${fmt.format(new Date(r.startUtc))}</span><span>◷ ${status(r)==='upcoming'?rel(new Date(r.startUtc)):status(r)==='live'?'läuft jetzt':'beendet'}</span></div><div class="pills">${classes(r)}</div><span class="cta">RACE CENTER →</span></a>`; }
function pageHead(kicker,title,sub=''){ return `<section class="page-head"><div class="kicker">${esc(kicker)}</div><h1>${esc(title)}</h1>${sub?`<p>${esc(sub)}</p>`:''}</section>`; }

async function renderHub(){ const c=await core(), now=new Date(); const sorted=[...c.races].sort((a,b)=>{const o={live:0,upcoming:1,finished:2}; return o[status(a)]-o[status(b)] || new Date(a.startUtc)-new Date(b.startUtc)}); const featured=sorted.find(r=>status(r)==='live')||sorted.find(r=>status(r)==='upcoming')||sorted[0]; const rest=sorted.filter(r=>r!==featured); shell(`${pageHead('ENDURANCE & GT DASHBOARD','RACE PIT WALL','WEC · IMSA · ELMS · GTWC · NLS · DTM · ADAC GT Masters · IGTC')} ${featured?hero(featured,c):''}<section class="section-title"><h2>Race Radar</h2><a href="${BASE}rennen.html">ALLE RENNEN →</a></section><div class="grid">${rest.slice(0,11).map(r=>raceCard(r,c)).join('')}</div>`,'Pit Wall'); }

function selectedCsv(k){return (q(k)||'').split(',').filter(Boolean)}
function toggleUrl(key,val){ const p=new URLSearchParams(location.search),arr=(p.get(key)||'').split(',').filter(Boolean); p.set(key,arr.includes(val)?arr.filter(x=>x!==val).join(','):[...arr,val].join(',')); if(!p.get(key))p.delete(key); return `${BASE}rennen.html${p.toString()?'?'+p:''}`; }
async function renderRaces(){ const c=await core(), ss=selectedCsv('series'),cs=selectedCsv('class'),sts=selectedCsv('status'); const list=c.races.filter(r=>(!ss.length||ss.includes(r.seriesSlug))&&(!cs.length||cs.some(x=>(r.classTags||[]).includes(x)))&&(!sts.length||sts.includes(status(r)))); const seriesChips=c.series.map(s=>`<a class="chip ${ss.includes(s.slug)?'on':''}" href="${toggleUrl('series',s.slug)}">${esc(s.shortName)}</a>`).join(''); const classOpts=['HYPERCAR','GTP','LMP2','LMP3','GT3','GT4']; const classChips=classOpts.map(x=>`<a class="chip ${cs.includes(x)?'on':''}" href="${toggleUrl('class',x)}">${x}</a>`).join(''); const stChips=['upcoming','live','finished'].map(x=>`<a class="chip ${sts.includes(x)?'on':''}" href="${toggleUrl('status',x)}">${statusLabel(x)}</a>`).join(''); shell(`${pageHead('RACE DATABASE','Rennen',`${list.length} von ${c.races.length} Rennen`)}<div class="filters"><label>SERIE<div>${seriesChips}</div></label><label>KLASSE<div>${classChips}</div></label><label>STATUS<div>${stChips}</div></label><a class="reset" href="${BASE}rennen.html">FILTER ZURÜCKSETZEN</a></div><div class="grid">${list.map(r=>raceCard(r,c)).join('')}</div>`,'Rennen'); }

async function renderCalendar(){ const c=await core(); const arr=[...c.races].sort((a,b)=>new Date(a.startUtc)-new Date(b.startUtc)); const groups=new Map(); for(const r of arr){const d=new Date(r.startUtc),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`; if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)} let html=''; for(const [k,rs] of groups){ const d=new Date(rs[0].startUtc),title=new Intl.DateTimeFormat('de-DE',{month:'long',year:'numeric'}).format(d); html+=`<section class="month"><h2>${title}</h2>${rs.map(r=>{const s=c.seriesMap.get(r.seriesSlug),t=c.trackMap.get(r.trackSlug);return `<a class="cal-row ${status(r)}" href="${BASE}race.html?slug=${r.slug}"><time>${new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}).format(new Date(r.startUtc))}</time><b>${esc(r.name)}</b><span>${esc(s?.shortName||'')} · ${esc(t?.name||'')}</span>${badge(r)}</a>`}).join('')}</section>`} shell(`${pageHead('SEASON VIEW','Kalender','Alle hinterlegten Rennen chronologisch')}<div class="calendar">${html}</div>`,'Kalender'); }

async function renderSeries(){ const c=await core(); const cards=c.series.map(s=>{const rs=c.races.filter(r=>r.seriesSlug===s.slug),up=rs.filter(r=>status(r)==='upcoming').sort((a,b)=>new Date(a.startUtc)-new Date(b.startUtc))[0]; return `<a class="series-card" href="${BASE}serie.html?slug=${s.slug}"><div class="series-code">${esc(s.shortName)}</div><h2>${esc(s.name)}</h2><p>${esc(s.description||'')}</p><div class="pills">${(s.canonicalClasses||s.classes||[]).map(x=>`<span class="pill">${esc(x)}</span>`).join('')}</div><div class="stats"><span><b>${rs.length}</b> Rennen</span><span><b>${rs.filter(r=>status(r)==='finished').length}</b> beendet</span></div><small>${up?`Als nächstes: ${esc(up.name)} · ${fmt.format(new Date(up.startUtc))}`:'Keine weiteren Rennen hinterlegt'}</small></a>`}).join(''); shell(`${pageHead('CHAMPIONSHIPS','Serien','Die wichtigsten Endurance- und GT-Serien im Dashboard')}<div class="series-grid">${cards}</div>`,'Serien'); }

async function renderSeriesDetail(){ const c=await core(),slug=q('slug')||q('id'),s=c.seriesMap.get(slug); if(!s)return render404('Serie nicht gefunden'); const rs=c.races.filter(r=>r.seriesSlug===slug).sort((a,b)=>new Date(a.startUtc)-new Date(b.startUtc)); shell(`${pageHead(s.shortName,s.name,s.description||'')}<div class="detail-actions">${s.officialUrl?`<a target="_blank" rel="noopener" href="${esc(s.officialUrl)}">OFFIZIELLE WEBSITE ↗</a>`:''}${s.youtubeUrl?`<a target="_blank" rel="noopener" href="${esc(s.youtubeUrl)}">YOUTUBE ↗</a>`:''}</div><div class="grid">${rs.map(r=>raceCard(r,c)).join('')}</div>` ,s.shortName); }

function countdownHtml(r){ return `<div class="countdown" data-start="${esc(r.startUtc)}" data-end="${esc(r.endUtc)}"><div class="count-label">COUNTDOWN</div><div class="count-value">--:--:--</div></div>`; }
function startCountdown(){ const e=document.querySelector('.countdown'); if(!e)return; const v=e.querySelector('.count-value'),l=e.querySelector('.count-label'); const a=new Date(e.dataset.start),b=new Date(e.dataset.end); const f=()=>{const now=new Date(); let ms; if(now<a){l.textContent='COUNTDOWN BIS START';ms=a-now}else if(now<=b){l.textContent='RENNEN LÄUFT · RESTZEIT';ms=b-now}else{l.textContent='RENNEN BEENDET';v.textContent='ZIELFLAGGE';return} const s=Math.max(0,Math.floor(ms/1000)),d=Math.floor(s/86400),h=Math.floor((s%86400)/3600),m=Math.floor((s%3600)/60),sec=s%60; v.textContent=`${d?d+'T ':''}${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}`};f();setInterval(f,1000); }
async function richDetail(slug){ try{return await load(`races/${slug}.json`)}catch{return null} }
async function weather(track){ const e=document.querySelector('#weather'); if(!e||!track?.lat)return; try{const p=new URLSearchParams({latitude:track.lat,longitude:track.lng,current_weather:'true',timezone:'auto'}),r=await fetch(`https://api.open-meteo.com/v1/forecast?${p}`);if(!r.ok)throw 0;const d=await r.json(),w=d.current_weather;e.innerHTML=`<div class="weather-now"><b>${Math.round(w.temperature)}°C</b><span>Wind ${Math.round(w.windspeed)} km/h</span><small>${esc(track.name)}</small></div>`}catch{e.innerHTML='<p class="muted">Wetter momentan nicht verfügbar.</p>'}}
async function news(detail){ const e=document.querySelector('#news'); if(!e)return; const feeds=[...(detail?.newsFeeds||[])]; try{const cfg=await load('config.json');feeds.push(...(cfg.globalNewsFeeds||[]))}catch{} if(!feeds.length){e.innerHTML='<p class="muted">Keine News-Feeds hinterlegt.</p>';return} const items=[]; for(const f of feeds.slice(0,2)){try{const u=`https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(f.url)}`,r=await fetch(u);if(!r.ok)continue;const d=await r.json();for(const it of (d.items||[]).slice(0,4))items.push({...it,source:f.label})}catch{}} items.sort((a,b)=>new Date(b.pubDate)-new Date(a.pubDate)); e.innerHTML=items.length?items.slice(0,6).map(x=>`<a class="news-item" target="_blank" rel="noopener" href="${esc(x.link)}"><small>${esc(x.source)}</small><b>${esc(x.title)}</b><span>${x.pubDate?rel(new Date(x.pubDate)):''}</span></a>`).join(''):'<p class="muted">News momentan nicht verfügbar.</p>'; }
async function renderRace(){ const c=await core(),slug=q('slug')||q('id'),r=c.races.find(x=>x.slug===slug); if(!r)return render404('Rennen nicht gefunden'); const d=await richDetail(slug),s=c.seriesMap.get(r.seriesSlug),t=c.trackMap.get(r.trackSlug),detail={...r,...(d||{})}; const schedule=(detail.schedule||[]).map(x=>`<div class="schedule-row"><time>${esc(x.date)} · ${esc(x.time)}</time><b>${esc(x.event)}</b></div>`).join('')||'<p class="muted">Zeitplan wird nachgepflegt.</p>'; const links=(detail.quicklinks||[]).map(x=>`<a class="quick" target="_blank" rel="noopener" href="${esc(x.url)}"><b>${esc(x.label)}</b><span>${esc(x.sub||'Öffnen')} ↗</span></a>`).join(''); shell(`<a class="back" href="${BASE}rennen.html">← ZURÜCK ZU RENNEN</a><section class="race-hero"><div>${badge(r)} <span class="series">${esc(s?.shortName||'')}</span></div><h1>${esc(r.name)}</h1><p>⌖ ${esc(t?.name||r.trackSlug)} · ${fmt.format(new Date(r.startUtc))} · ${duration(r)}</p><div class="pills">${classes(r)}</div></section>${countdownHtml(r)}<div class="two-col"><section class="panel"><h2>Wetter</h2><div id="weather"><p class="muted">Wetter lädt …</p></div></section><section class="panel"><h2>Stream & Serie</h2>${s?.youtubeUrl?`<a class="big-link" target="_blank" rel="noopener" href="${esc(s.youtubeUrl)}">${esc(s.shortName)} AUF YOUTUBE ↗</a>`:'<p class="muted">Kein YouTube-Channel hinterlegt.</p>'}${s?.officialUrl?`<a class="text-link" target="_blank" rel="noopener" href="${esc(s.officialUrl)}">Offizielle Serienseite ↗</a>`:''}</section></div><section class="panel"><h2>Zeitplan</h2>${schedule}</section>${detail.liveTimingUrl?`<section class="panel"><h2>Live Timing</h2><a class="big-link" target="_blank" rel="noopener" href="${esc(detail.liveTimingUrl)}">LIVE TIMING ÖFFNEN ↗</a></section>`:''}${links?`<section class="panel"><h2>Quicklinks</h2><div class="quick-grid">${links}</div></section>`:''}<section class="panel"><h2>News</h2><div id="news"><p class="muted">News lädt …</p></div></section>`,r.name); startCountdown(); weather(t); news(detail); }

function getWatch(){try{return JSON.parse(localStorage.getItem('rpw-watchlist')||'[]')}catch{return[]}}
function setWatch(x){localStorage.setItem('rpw-watchlist',JSON.stringify(x))}
async function renderWatch(){ const c=await core(); let ids=getWatch(); const available=c.races.filter(r=>status(r)!=='finished').sort((a,b)=>new Date(a.startUtc)-new Date(b.startUtc)); const selected=c.races.filter(r=>ids.includes(r.slug)); shell(`${pageHead('LOCAL WATCHLIST','Watchlist','Deine Auswahl bleibt nur in diesem Browser gespeichert.')}<section class="panel"><h2>Meine Rennen</h2><div id="watch-selected" class="grid">${selected.length?selected.map(r=>raceCard(r,c)).join(''):'<p class="muted">Noch keine Rennen ausgewählt.</p>'}</div></section><section class="panel"><h2>Rennen hinzufügen</h2><div class="watch-options">${available.map(r=>`<label><input type="checkbox" data-watch="${r.slug}" ${ids.includes(r.slug)?'checked':''}> <b>${esc(r.name)}</b><span>${fmt.format(new Date(r.startUtc))}</span></label>`).join('')}</div></section><div class="detail-actions"><button id="export-watch">EXPORTIEREN</button><label class="buttonlike">IMPORTIEREN<input hidden type="file" id="import-watch" accept="application/json"></label></div>`,'Watchlist'); document.querySelectorAll('[data-watch]').forEach(e=>e.addEventListener('change',()=>{const slug=e.dataset.watch; ids=e.checked?[...new Set([...ids,slug])]:ids.filter(x=>x!==slug);setWatch(ids);renderWatch()})); document.querySelector('#export-watch')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify(ids,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='race-pit-wall-watchlist.json';a.click();URL.revokeObjectURL(a.href)}); document.querySelector('#import-watch')?.addEventListener('change',async(e)=>{try{const arr=JSON.parse(await e.target.files[0].text());if(Array.isArray(arr)){setWatch(arr);renderWatch()}}catch{alert('Ungültige Watchlist-Datei.')}}); }

function renderAbout(){ shell(`${pageHead('ABOUT','RACE PIT WALL','Ein inoffizielles Motorsport-Dashboard für Endurance- und GT-Fans.')}<div class="two-col"><section class="panel"><h2>Was ist das?</h2><p>RACE PIT WALL bündelt Renntermine, Status, Serien, Strecken, Wetter, Zeitpläne und weiterführende Links in einer Oberfläche.</p><p>Das Projekt ist ein Fan-Dashboard und steht in keiner Verbindung zu FIA, ACO, ADAC, SRO, Nürburgring oder anderen Veranstaltern.</p></section><section class="panel"><h2>Daten & Technik</h2><p>Renn-, Serien- und Streckendaten werden als JSON gepflegt. Wetter kommt von Open-Meteo. News werden – soweit verfügbar – über rss2json geladen.</p><p>Die Seite wird mit Vite gebaut und über GitHub Pages bereitgestellt.</p></section></div><section class="panel"><h2>Datenquellen</h2><p>Termine und Links wurden aus den im Projekt hinterlegten Quellen übernommen. Einzelne Termine oder Startzeiten sind als TBC/Näherung markiert. Angaben ohne Gewähr.</p></section>`,'About'); }
function render404(msg='Seite nicht gefunden'){ shell(`${pageHead('BOX BOX','404',msg)}<a class="big-link" href="${BASE}">ZURÜCK ZUR PIT WALL →</a>`,'404'); }

(async()=>{ try{ if(page==='hub')await renderHub(); else if(page==='races')await renderRaces(); else if(page==='calendar')await renderCalendar(); else if(page==='series')await renderSeries(); else if(page==='series-detail')await renderSeriesDetail(); else if(page==='race-detail')await renderRace(); else if(page==='watchlist')await renderWatch(); else if(page==='about')renderAbout(); else render404(); }catch(e){ console.error(e); shell(`<section class="error"><h1>DATEN-LADEFEHLER</h1><p>${esc(e.message)}</p><a href="${BASE}">Zurück zur Startseite</a></section>`,'Fehler'); } })();
